version: "3"
services:
  nginx:
    build:
      context: ./nginx
    image: kugmax/udacity-c3-nginx
  user_service:
    build:
      context: ./udactiy-c3-user
    image: kugmax/udacity-c3-user
  feed_service:
    build:
      context: ./udacity-c3-feed
    image: kugmax/udacity-c3-feed
  frontend_service:
    build:
      context: ./udacity-c3-frontend 
    image: kugmax/udacity-c3-frontend