apiVersion: v1
kind: Service
metadata:
  labels:
    service: frontend-service
  name: frontend-service
spec:
  ports:
  - name: "8100"
    port: 8100
    targetPort: 80
  selector:
    service: frontend-service
#  type: LoadBalancer  