apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: frontend-service
  name: frontend-service
spec:
  replicas: 2
  selector:
    matchLabels:
      service: frontend-service
  template:
    metadata:
      labels:
        service: frontend-service
        api: external        
    spec:
      containers:
      - image: kugmax/udacity-c3-frontend
        name: frontend-service
        imagePullPolicy: Always          
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"                
      restartPolicy: Always